export const API_ENDPOINTS = {
  CATEGORIES: "date/skipcategories",
  PRODUCTS: "date/hot_deals",
  POPULAR_PRODUCTS: "date/special_deals",
  SETTINGS: "site/setting",
  CUSTOMER: "user/date",
  new : "date/new",
  SINGLEVENDOR : "vendor/details/",
  VENDORS : "All/vendor/List" , 
  search : "search" ,
  slider : "slider" , 
  ONEPRODUCT : "product/details/" ,
  COUPONS: "coupons",
  PARENT_CATEGORIES: "categories",
  FEATURED_CATEGORIES: "featured-categories",
  TYPE: "types",
  UPLOAD: "attachments",
  ORDER: "orders",
  // ORDER_STATUS: "order-status",
  LOGIN: "user/login",
  SOCIAL_LOGIN: "social-login-token",
  REGISTER: "user/register",
  FORGET_PASSWORD: "forget-password",
  LOGOUT: "logout",
  CHANGE_PASSWORD: "change-password",
  RESET_PASSWORD: "reset-password",
  VERIFY_FORGET_PASSWORD: "verify-forget-password-token",
  VERIFY_CHECKOUT: "orders/checkout/verify",
  CONTACT: "contact-us",
  ADDRESS: "address",
  ATTRIBUTES: "attributes",
  SHOPS: "shops",
  ORDERS: "orders",
  SEND_OTP_CODE: "send-otp-code",
  VERIFY_OTP_CODE: "verify-otp-code",
  OTP_LOGIN: "otp-login",
  UPDATE_CONTACT: "update-contact",
  CUSTOMERS: "users",
  TAGS: "tags",
  INSTAGRAM: `${process.env.NEXT_PUBLIC_INSTAGRAM_URL}&access_token=${process.env.NEXT_PUBLIC_INSTAGRAM_BASIC_DISPLAY_USER_TOKEN}`,
  INSTAGRAM_TOKEN: process.env.NEXT_PUBLIC_INSTAGRAM_BASIC_DISPLAY_USER_TOKEN,
  CARDS: '/cards',
  SET_DEFAULT_CARD: '/set-default-card',
  SAVE_PAYMENT_METHOD: '/save-payment-method',
  PAYMENT_INTENT: '/payment-intent',
  ORDERS_PAYMENT: '/orders/payment',
};
